class VimSyntax
	Scripts =
	[
		['a2ps', 'a2ps(1) configuration file'],
		['a65', 'xa 6502 cross assembler'],
		['aap', 'A-A-P recipe'],
		['abap', 'SAP - ABAP/R4'],
		['abaqus', 'Abaqus finite element input file (www.hks.com)'],
		['abc', 'abc music notation language'],
		['abel', 'ABEL'],
		['acedb', 'AceDB model files'],
		['ada', 'Ada (2005)'],
		['aflex', 'AfLex (from Lex syntax file)'],
		['ahdl', 'Altera AHDL'],
		['alsaconf', 'alsaconf(8) configuration file'],
		['amiga', 'AmigaDos'],
		['aml', 'AML (ARC/INFO Arc Macro Language)'],
		['ampl', 'ampl (A Mathematical Programming Language)'],
		['ant', 'ANT build file (xml)'],
		['apache', 'Apache configuration (httpd.conf, srm.conf, access.conf, .htaccess)'],
		['apachestyle', 'Apache-Style configuration files (proftpd.conf/apache.conf/..)'],
		['arch', 'GNU Arch inventory file'],
		['art', 'ART-IM and ART*Enterprise'],
		['asm', 'GNU Assembler'],
		['asm68k', 'Motorola 68000 Assembler'],
		['asmh8300', 'Hitachi H-8300h specific syntax for GNU Assembler'],
		['asn', 'ASN.1'],
		['aspperl', 'Active State\'s PerlScript (ASP)'],
		['aspvbs', 'Microsoft VBScript Web Content (ASP)'],
		['asterisk', 'Asterisk config file'],
		['asteriskvm', 'Asterisk voicemail config file'],
		['atlas', 'ATLAS'],
		['autohotkey', 'AutoHotkey script file'],
		['autoit', 'AutoIt v3 (http://www.autoitscript.com/autoit3/)'],
		['automake', 'automake Makefile.am'],
		['ave', 'avenue'],
		['awk', 'awk, nawk, gawk, mawk'],
		['ayacc', 'AYacc'],
		['b', 'B (A Formal Method with refinement and mathematical proof)'],
		['baan', 'Baan'],
		['basic', 'BASIC'],
		['bc', 'bc - An arbitrary precision calculator language'],
		['bdf', 'BDF font definition'],
		['bib', 'BibTeX (bibliographic database format for (La)TeX)'],
		['bindzone', 'BIND zone files (RFC1035)'],
		['blank', 'Blank 1.4.1'],
		['bst', 'BibTeX Bibliography Style'],
		['btm', '4Dos batch file'],
		['bzr', 'Bazaar (bzr) commit file'],
		['c', 'C', true],
		['calendar', 'calendar(1) input file'],
		['catalog', 'sgml catalog file'],
		['cdl', 'Comshare Dimension Definition Language'],
		['cdrdaoconf', 'cdrdao(1) configuration file'],
		['cdrtoc', 'cdrdao(1) TOC file'],
		['cf', 'ColdFusion'],
		['cfg', 'Good old CFG files'],
		['ch', 'Ch'],
		['change', 'WEB Changes'],
		['changelog', 'generic ChangeLog file'],
		['chaskell', 'Haskell supporting c2hs binding hooks'],
		['cheetah', 'Cheetah template engine'],
		['chill', 'CHILL'],
		['chordpro', 'ChordPro (v. 3.6.2)'],
		['cl', 'cl ("Clever Language" by Multibase, http://www.mbase.com.au)'],
		['clean', 'Clean'],
		['clipper', 'Clipper 5.2 & FlagShip'],
		['cmake', 'VIM'],
		['cobol', 'COBOL'],
		['coco', 'Coco/R'],
		['conaryrecipe', 'Conary Recipe'],
		['conf', 'generic configure file'],
		['config', 'configure.in script: M4 with sh'],
		['context', 'ConTeXt typesetting engine'],
		['cpp', 'C++', true],
		['crm', 'CRM114'],
		['crontab', 'crontab'],
		['cs', 'C#', true],
		['csc', 'Essbase script'],
		['csh', 'C-shell (csh)'],
		['csp', 'CSP (Communication Sequential Processes, using FDR input syntax)'],
		['css', 'Cascading Style Sheets'],
		['cterm', 'Century Term Command Script'],
		['ctrlh', 'CTRL-H (e.g., ASCII manpages)'],
		['cuda', 'CUDA (NVIDIA Compute Unified Device Architecture)'],
		['cupl', 'CUPL'],
		['cuplsim', 'CUPL simulation'],
		['cvs', 'CVS commit file'],
		['cvsrc', 'cvs(1) RC file'],
		['cweb', 'CWEB'],
		['cynlib', 'Cynlib(C++)'],
		['cynpp', 'Cyn++'],
		['d', 'D'],
		['dcd', 'WildPackets EtherPeek Decoder (.dcd) file'],
		['dcl', 'DCL (Digital Command Language - vms)'],
		['debchangelog', 'Debian changelog files'],
		['debcontrol', 'Debian control files'],
		['debsources', 'Debian sources.list'],
		['def', 'Microsoft Module-Definition (.def) File'],
		['denyhosts', 'denyhosts configuration file'],
		['desc', 'T2 / ROCK Linux .desc'],
		['desktop', '.desktop, .directory files'],
		['dictconf', 'dict(1) configuration file'],
		['dictdconf', 'dictd(8) configuration file'],
		['diff', 'Diff (context or unified)'],
		['dircolors', 'dircolors(1) input file'],
		['diva', 'SKILL for Diva'],
		['django', 'Django template'],
		['dns', 'DNS/BIND Zone File'],
		['docbk', 'DocBook'],
		['docbksgml', 'DocBook SGML'],
		['docbkxml', 'DocBook XML'],
		['dosbatch', 'MSDOS batch file (with NT command extensions)'],
		['dosini', 'Configuration File (ini file) for MSDOS/MS Windows'],
		['dot', 'Dot'],
		['doxygen', 'doxygen on top of c, cpp, idl, java, php'],
		['dracula', 'Dracula'],
		['dsl', 'DSSSL'],
		['dtd', 'DTD (Document Type Definition for XML)'],
		['dtml', 'Zope\'s Dynamic Template Markup Language'],
		['dtrace', 'D script as described in "Solaris Dynamic Tracing Guide",'],
		['dylan', 'Dylan'],
		['dylanintr', 'Dylan'],
		['dylanlid', 'Dylan Library Interface Files'],
		['ecd', 'ecd (Embedix Component Description) files'],
		['edif', 'EDIF (Electronic Design Interchange Format)'],
		['eiffel', 'Eiffel'],
		['elf', 'ELF'],
		['elinks', 'elinks(1) configuration file'],
		['elmfilt', 'Elm Filter rules'],
		['erlang', 'erlang (ERicsson LANGuage)', true],
		['eruby', 'eRuby'],
		['esmtprc', 'Esmtp setup file (based on esmtp 0.5.0)'],
		['esqlc', 'ESQL-C'],
		['esterel', 'ESTEREL'],
		['eterm', 'eterm(1) configuration file'],
		['eviews', 'Eviews (http://www.eviews.com)'],
		['exim', 'Exim configuration file exim.conf'],
		['expect', 'Expect'],
		['exports', 'exports'],
		['fasm', 'Flat Assembler (FASM)'],
		['fdcc', 'fdcc or locale files'],
		['fetchmail', 'fetchmail(1) RC File'],
		['fgl', 'Informix 4GL'],
		['flexwiki', 'FlexWiki, http://www.flexwiki.com/'],
		['focexec', 'Focus Executable'],
		['form', 'FORM'],
		['forth', 'FORTH'],
		['fortran', 'Fortran95 (and Fortran90, Fortran77, F and elf90)'],
		['foxpro', 'FoxPro for DOS/UNIX v2.6'],
		['framescript', 'FrameScript v4.0'],
		['freebasic', 'FreeBasic'],
		['fstab', 'fstab file'],
		['fvwm', 'Fvwm{1,2} configuration file'],
		['fvwm2m4', 'FvwmM4 preprocessed Fvwm2 configuration files'],
		['gdb', 'GDB command files'],
		['gdmo', 'GDMO'],
		['gedcom', 'Gedcom'],
		['git', 'generic git output'],
		['gitcommit', 'git commit file'],
		['gitconfig', 'git config file'],
		['gitrebase', 'git rebase --interactive'],
		['gitsendemail', 'git send-email message'],
		['gkrellmrc', 'gkrellm theme files `gkrellmrc\''],
		['gnuplot', 'gnuplot 3.8i.0'],
		['gp', 'gp (version 2.4)'],
		['gpg', 'gpg(1) configuration file'],
		['grads', 'grads (GrADS scripts)'],
		['gretl', 'gretl (http://gretl.sf.net)'],
		['groff', 'groff'],
		['groovy', 'Groovy'],
		['group', 'group(5) user group file'],
		['grub', 'grub(8) configuration file'],
		['gsp', 'GSP - GNU Server Pages (v. 0.86)'],
		['gtkrc', 'Gtk+ theme files `gtkrc\''],
		['haml', 'Haml'],
		['hamster', 'Hamster Scripting Language'],
		['haskell', 'Haskell', true],
		['haste', 'HASTE - a language for VLSI IC programming'],
		['hastepreproc', 'Haste preprocessor files'],
		['hb', 'Hyper Builder'],
		['help', 'Vim help file'],
		['hercules', 'Hercules'],
		['hex', 'Intel hex MCS51'],
		['hitest', 'none; used to see highlighting'],
		['hog', 'Snort Configuration File (see: http://www.snort.org)'],
		['hostconf', 'host.conf(5) configuration file'],
		['html', 'HTML'],
		['htmlcheetah', 'HTML with Cheetah tags'],
		['htmldjango', 'Django HTML template'],
		['htmlm4', 'HTML and M4'],
		['htmlos', 'HTML/OS by Aestiva'],
		['ia64', 'IA-64 (Itanium) assembly language'],
		['ibasic', 'ibasic'],
		['icemenu', 'Icewm Menu'],
		['icon', 'Icon'],
		['idl', 'IDL (Interface Description Language)'],
		['indent', 'indent(1) configuration file'],
		['inform', 'Inform'],
		['initex', 'TeX (core definition)'],
		['initng', 'initng .i files'],
		['inittab', 'SysV-compatible init process control file `inittab\''],
		['ipfilter', 'ipfilter configuration file'],
		['ishd', 'InstallShield Script'],
		['iss', 'Inno Setup File (iss file) and My InnoSetup extension'],
		['ist', 'Makeindex style file, *.ist'],
		['jal', 'JAL'],
		['jam', 'JAM'],
		['jargon', 'Jargon File'],
		['java', 'Java'],
		['javacc', 'JavaCC, a Java Compiler Compiler written by JavaSoft'],
		['javascript', 'JavaScript', true],
		['jess', 'Jess'],
		['jgraph', 'jgraph (graph plotting utility)'],
		['jproperties', 'Java Properties resource file (*.properties[_*])'],
		['jsp', 'JSP (Java Server Pages)'],
		['kix', 'KixTart 95, Kix2001 Windows script language http://kixtart.org/'],
		['kscript', 'kscript'],
		['kwt', 'kimwitu++'],
		['lace', 'lace'],
		['latte', 'Latte'],
		['ld', 'ld(1) script'],
		['ldapconf', 'ldap.conf(5) configuration file.'],
		['ldif', 'LDAP LDIF'],
		['lex', 'Lex'],
		['lftp', 'lftp(1) configuration file'],
		['lhaskell', 'Haskell with literate comments, Bird style,'],
		['libao', 'libao.conf(5) configuration file'],
		['lifelines', 'LifeLines (v 3.0.50) http://lifelines.sourceforge.net'],
		['lilo', 'lilo configuration (lilo.conf)'],
		['limits', 'limits(5) configuration file'],
		['lisp', 'Lisp', true],
		['lite', 'lite'],
		['litestep', 'LiteStep RC file'],
		['loginaccess', 'login.access(5) configuration file'],
		['logindefs', 'login.defs(5) configuration file'],
		['logtalk', 'Logtalk'],
		['lotos', 'LOTOS (Language Of Temporal Ordering Specifications, IS8807)'],
		['lout', 'Lout'],
		['lpc', 'LPC'],
		['lprolog', 'LambdaProlog (Teyjus)'],
		['lscript', 'LotusScript'],
		['lsl', 'Linden Scripting Language'],
		['lss', 'Lynx 2.7.1 style file'],
		['lua', 'Lua 4.0, Lua 5.0 and Lua 5.1', true],
		['lynx', 'Lynx configuration file (lynx.cfg)'],
		['m4', 'M4'],
		['mail', 'Mail file'],
		['mailaliases', 'aliases(5) local alias database file'],
		['mailcap', 'Mailcap configuration file'],
		['make', 'Makefile'],
		['man', 'Man page'],
		['manconf', 'man.conf(5) - man configuration file'],
		['maple', 'Maple V (based on release 4)'],
		['masm', 'Microsoft Macro Assembler (80x86)', true],
		['mason', 'Mason (Perl embedded in HTML)'],
		['master', 'Focus Master File'],
		['matlab', 'Matlab'],
		['maxima', 'Maxima (symbolic algebra program)'],
		['mel', 'MEL (Maya Extension Language)'],
		['messages', '/var/log/messages file'],
		['mf', 'Metafont'],
		['mgl', 'MGL'],
		['mgp', 'mgp - MaGic Point'],
		['mib', 'Vim syntax file for SNMPv1 and SNMPv2 MIB and SMI files'],
		['mma', 'Mathematica'],
		['mmix', 'MMIX'],
		['mmp', 'Symbian meta-makefile definition (MMP)'],
		['modconf', 'modules.conf(5) configuration file'],
		['model', 'Model'],
		['modsim3', 'Modsim III, by compuware corporation (www.compuware.com)'],
		['modula2', 'Modula 2'],
		['modula3', 'Modula-3'],
		['monk', 'Monk (See-Beyond Technologies)'],
		['moo', 'MOO'],
		['mp', 'MetaPost'],
		['mplayerconf', 'mplayer(1) configuration file'],
		['msidl', 'MS IDL (Microsoft dialect of Interface Description Language)'],
		['msmessages', 'MS Message Text files (*.mc)'],
		['msql', 'msql'],
		['mupad', 'MuPAD source'],
		['muttrc', 'Mutt setup files'],
		['mysql', 'mysql'],
		['named', 'BIND configuration file'],
		['nanorc', 'nanorc(5) - GNU nano configuration file'],
		['nasm', 'NASM - The Netwide Assembler (v0.98)'],
		['nastran', 'NASTRAN input/DMAP'],
		['natural', 'NATURAL'],
		['ncf', 'Novell "NCF" Batch File'],
		['netrc', 'netrc(5) configuration file'],
		['nqc', 'NQC - Not Quite C, for LEGO mindstorms'],
		['nroff', 'nroff/groff'],
		['nsis', 'NSIS script, for version of NSIS 1.91 and later'],
		['objc', 'Objective C'],
		['objcpp', 'Objective C++'],
		['ocaml', 'OCaml'],
		['occam', 'occam'],
		['omnimark', 'Omnimark'],
		['openroad', 'CA-OpenROAD'],
		['opl', 'OPL'],
		['ora', 'Oracle config files (.ora) (Oracle 8i, ver. 8.1.5)'],
		['pamconf', 'pam(8) configuration file'],
		['papp', 'papp'],
		['pascal', 'Pascal'],
		['passwd', 'passwd(5) password file'],
		['pccts', 'PCCTS'],
		['pdf', 'PDF'],
		['perl', 'Perl', true],
		['pf', 'OpenBSD packet filter configuration (pf.conf)'],
		['pfmain', 'Postfix main.cf configuration'],
		['php', 'php PHP 3/4/5', true],
		['pic', 'PIC16F84 Assembler (Microchip\'s microcontroller)'],
		['pike', 'Pike'],
		['pilrc', 'pilrc - a resource compiler for Palm OS development'],
		['pine', 'Pine (email program) run commands'],
		['pinfo', 'pinfo(1) configuration file'],
		['plaintex', 'TeX (plain.tex format)'],
		['plm', 'PL/M'],
		['plp', 'PLP (Perl in HTML)'],
		['plsql', 'Oracle Procedureal SQL (PL/SQL)'],
		['po', 'po (gettext)'],
		['pod', 'Perl POD format'],
		['postscr', 'PostScript - all Levels, selectable'],
		['pov', 'PoV-Ray(tm) 3.5 Scene Description Language'],
		['povini', 'PoV-Ray(tm) 3.5 configuration/initialization files'],
		['ppd', 'PPD (PostScript printer description) file'],
		['ppwiz', 'PPWizard (preprocessor by Dennis Bareis)'],
		['prescribe', 'Kyocera PreScribe2e'],
		['privoxy', 'Privoxy actions file'],
		['procmail', 'Procmail definition file'],
		['progress', 'Progress 4GL'],
		['prolog', 'PROLOG'],
		['promela', 'ProMeLa'],
		['protocols', 'protocols(5) - Internet protocols definition file'],
		['psf', 'Software Distributor product specification file'],
		['ptcap', 'printcap/termcap database'],
		['purifylog', 'purify log files'],
		['pyrex', 'Pyrex'],
		['python', 'Python', true],
		['qf', 'Quickfix window'],
		['quake', 'Quake[1-3] configuration file'],
		['r', 'R (GNU S)'],
		['racc', 'Racc input file'],
		['radiance', 'Radiance Scene Description'],
		['ratpoison', 'Ratpoison configuration/commands file ( /etc/ratpoisonrc ~/.ratpoisonrc )'],
		['rc', 'M$ Resource files (*.rc)'],
		['rcs', 'RCS file'],
		['rcslog', 'RCS log output'],
		['readline', 'readline(3) configuration file'],
		['rebol', 'Rebol'],
		['registry', 'Windows Registry export with regedit (*.reg)'],
		['remind', 'Remind'],
		['resolv', 'resolver configuration file'],
		['reva', 'Reva Forth'],
		['rexx', 'Rexx'],
		['rhelp', 'R Help File'],
		['rib', 'Renderman Interface Bytestream'],
		['rnc', 'Relax NG compact syntax'],
		['rnoweb', 'R noweb Files'],
		['robots', '"Robots.txt" files'],
		['rpcgen', 'rpcgen'],
		['rpl', 'RPL/2'],
		['rst', 'reStructuredText documentation format'],
		['rtf', 'Rich Text Format'],
		['ruby', 'Ruby', true],
		['samba', 'samba configuration files (smb.conf)'],
		['sas', 'SAS'],
		['sass', 'Sass'],
		['sather', 'Sather/pSather'],
		['scheme', 'Scheme (R5RS)', true],
		['screen', 'screen(1) configuration file'],
		['sd', 'streaming descriptor file'],
		['sdl', 'SDL'],
		['sed', 'sed'],
		['sendpr', 'FreeBSD send-pr file'],
		['sensors', 'sensors.conf(5) - libsensors configuration file'],
		['services', 'services(5) - Internet network services list'],
		['setserial', 'setserial(8) configuration file'],
		['sgml', 'SGML'],
		['sgmldecl', 'SGML (SGML Declaration <!SGML ...>)'],
		['sgmllnx', 'SGML-linuxdoc (supported by old sgmltools-1.x)'],
		['sh', 'shell (sh) Korn shell (ksh) bash (sh)', true],
		['sicad', 'SiCAD (procedure language)'],
		['sieve', 'Sieve filtering language input file'],
		['simula', 'Simula'],
		['sinda', 'sinda85, sinda/fluint input file'],
		['sindacmp', 'sinda85, sinda/fluint compare file'],
		['sindaout', 'sinda85, sinda/fluint output file'],
		['skill', 'SKILL'],
		['sl', 'Renderman shader language'],
		['slang', 'S-Lang'],
		['slice', 'Slice (ZeroC\'s Specification Language for Ice)'],
		['slpconf', 'RFC 2614 - An API for Service Location configuration file'],
		['slpreg', 'RFC 2614 - An API for Service Location registration file'],
		['slpspi', 'RFC 2614 - An API for Service Location SPI file'],
		['slrnrc', 'Slrn setup file (based on slrn 0.9.8.1)'],
		['slrnsc', 'Slrn score file (based on slrn 0.9.8.0)'],
		['sm', 'sendmail'],
		['smarty', 'Smarty Templates'],
		['smcl', 'SMCL -- Stata Markup and Control Language'],
		['smil', 'SMIL (Synchronized Multimedia Integration Language)'],
		['smith', 'SMITH'],
		['sml', 'SML'],
		['snnsnet', 'SNNS network file'],
		['snnspat', 'SNNS pattern file'],
		['snnsres', 'SNNS result file'],
		['snobol4', 'SNOBOL4'],
		['spec', 'SPEC: Build/install scripts for Linux RPM packages'],
		['specman', 'SPECMAN E-LANGUAGE'],
		['spice', 'Spice circuit simulator input netlist'],
		['splint', 'splint (C with lclint/splint Annotations)'],
		['spup', 'Speedup, plant simulator from AspenTech'],
		['spyce', 'SPYCE'],
		['sql', 'SQL', true],
		['sqlanywhere', 'SQL, Adaptive Server Anywhere'],
		['sqlforms', 'SQL*Forms (Oracle 7), based on sql.vim (vim5.0)'],
		['sqlinformix', 'SQL, SPL (Informix Dynamic Server 2000 v9.2)'],
		['sqlj', 'sqlj'],
		['sqloracle', 'SQL, PL/SQL (Oracle 8i)'],
		['sqr', 'Structured Query Report Writer (SQR)'],
		['squid', 'Squid config file'],
		['sshconfig', 'OpenSSH server configuration file (ssh_config)'],
		['sshdconfig', 'OpenSSH server configuration file (sshd_config)'],
		['st', 'Smalltalk'],
		['stata', 'Stata and/or Mata'],
		['stp', 'Stored Procedures (STP)'],
		['strace', 'strace output'],
		['sudoers', 'sudoers(5) configuration files'],
		['svn', 'Subversion (svn) commit file'],
		['sysctl', 'sysctl.conf(5) configuration file'],
		['tads', 'TADS'],
		['tags', 'tags'],
		['tak', 'TAK2, TAK3, TAK2000 thermal modeling input file'],
		['takcmp', 'TAK2, TAK3, TAK2000 thermal modeling compare file'],
		['takout', 'TAK2, TAK3, TAK2000 thermal modeling output file'],
		['tasm', 'TASM: turbo assembler by Borland'],
		['tcl', 'TCL/TK'],
		['terminfo', 'terminfo(5) definition'],
		['tex', 'TeX'],
		['texinfo', 'Texinfo (macro package for TeX)'],
		['texmf', 'Web2C TeX texmf.cnf configuration file'],
		['tf', 'tf'],
		['tidy', 'HMTL Tidy configuration file ( /etc/tidyrc ~/.tidyrc )'],
		['tilde', 'Tilde'],
		['tli', 'TealInfo source files (*.tli)'],
		['tpp', 'tpp - Text Presentation Program'],
		['trasys', 'TRASYS input file'],
		['trustees', 'trustees'],
		['tsalt', 'Telix (Modem Comm Program) SALT Script'],
		['tsscl', 'TSS (Thermal Synthesizer System) Command Line'],
		['tssgm', 'TSS (Thermal Synthesizer System) Geometry'],
		['tssop', 'TSS (Thermal Synthesizer System) Optics'],
		['uc', 'UnrealScript'],
		['udevconf', 'udev(8) configuration file'],
		['udevperm', 'udev(8) permissions file'],
		['udevrules', 'udev(8) rules file'],
		['uil', 'Motif UIL (User Interface Language)'],
		['updatedb', 'updatedb.conf(5) configuration file'],
		['valgrind', 'Valgrind Memory Debugger Output'],
		['vb', 'Visual Basic', true],
		['vera', 'Vera'],
		['verilog', 'Verilog'],
		['verilogams', 'Verilog-AMS'],
		['vgrindefs', 'Vgrindefs'],
		['vhdl', 'VHDL'],
		['vim', 'Vim 7.2 script'],
		['viminfo', 'Vim .viminfo file'],
		['virata', 'Virata AConfig Configuration Script'],
		['vmasm', '(VAX) Macro Assembly'],
		['voscm', 'VOS CM macro'],
		['vrml', 'VRML97'],
		['vsejcl', 'JCL job control language - DOS/VSE'],
		['wdiff', 'wDiff (wordwise diff)'],
		['web', 'WEB'],
		['webmacro', 'WebMacro'],
		['wget', 'Wget configuration file ( /etc/wgetrc ~/.wgetrc )'],
		['winbatch', 'WinBatch/Webbatch (*.wbt, *.web)'],
		['wml', 'WML - Website MetaLanguage'],
		['wsh', 'Windows Scripting Host'],
		['wsml', 'WSML'],
		['wvdial', 'Configuration file for WvDial'],
		['xbl', 'XBL 1.0'],
		['xdefaults', 'X resources files like ~/.Xdefaults (xrdb)'],
		['xf86conf', 'XF86Config (XFree86 configuration file)'],
		['xhtml', 'XHTML'],
		['xinetd', 'xinetd.conf(5) configuration file'],
		['xkb', 'XKB (X Keyboard Extension) components'],
		['xmath', 'xmath (a simulation tool)'],
		['xml', 'XML'],
		['xmodmap', 'xmodmap(1) definition file'],
		['xpm', 'X Pixmap'],
		['xpm2', 'X Pixmap v2'],
		['xquery', 'XQuery'],
		['xs', 'XS (Perl extension interface language)'],
		['xsd', 'XSD (XML Schema)'],
		['xslt', 'XSLT'],
		['xxd', 'bin using xxd'],
		['yacc', 'Yacc'],
		['yaml', 'YAML (YAML Ain\'t Markup Language)'],
		['z8a', 'Z80 assembler asz80'],
		['zsh', 'Zsh shell script'],
	]
end
